# Generated by Django 5.2.7 on 2025-10-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('account', 'profile_type'), name='uniq_account_profiletype'),
        ),
    ]
