# Generated by Django 5.2.7 on 2025-12-31 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_admin_deleted_profile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashoutReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cashed_out_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_reports', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Cashout Report',
                'verbose_name_plural': 'Cashout Reports',
            },
        ),
    ]
