# Generated by Django 5.2.7 on 2025-12-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_cashoutreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoutreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
