# Generated by Django 5.2.7 on 2025-11-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainercalendarslot',
            name='slot_end_time',
        ),
    ]
