# Generated by Django 5.2.7 on 2025-10-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_remove_trainer_specialty_trainer_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='trainer_profiles/'),
        ),
    ]
