# Generated by Django 5.2.7 on 2025-11-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_alter_trainer_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerexperience',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainerexperience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trainerexperience',
            name='work_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
