# Generated by Django 5.2.7 on 2025-11-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_alter_trainerexperience_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerexperience',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
