# Generated by Django 5.2.7 on 2025-11-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_trainerexperience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
