# Generated by Django 5.2.7 on 2025-12-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_alter_trainerexperience_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
