# Generated by Django 5.2.7 on 2025-12-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0007_trainer_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
