# Generated by Django 5.2.7 on 2025-12-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0008_alter_trainer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="Link to the trainer's profile picture", max_length=500, null=True),
        ),
    ]
