# Generated by Django 5.2.7 on 2025-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0009_alter_trainer_name_alter_trainer_profile_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainercalendarslot',
            options={'ordering': ['slot_start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='trainercalendarslot',
            unique_together={('trainer', 'slot_start_time')},
        ),
        migrations.AddField(
            model_name='trainercalendarslot',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainercalendarslot',
            name='slot_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='trainercalendarslot',
            name='is_booked',
        ),
        migrations.RemoveField(
            model_name='trainercalendarslot',
            name='slot_date',
        ),
    ]
