# Generated by Django 5.2.7 on 2025-12-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_alter_trainercalendarslot_options_and_more'),
    ]

    operations = []
