# Generated by Django 5.2.7 on 2025-12-20 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_account'),
        ('trainers', '0012_convert_time_to_datetime_for_calendar_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainercalendarslot',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
