# Generated by Django 5.2.7 on 2025-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0013_alter_trainercalendarslot_trainer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerspecialization',
            name='hourly_rate',
        ),
        migrations.AddField(
            model_name='trainer',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
