# Generated by Django 5.2.7 on 2025-12-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0014_remove_trainerspecialization_hourly_rate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='hourly_rate',
            new_name='rate',
        ),
    ]
