# Generated by Django 5.2.7 on 2025-12-21 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0015_rename_hourly_rate_trainer_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='rate',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
