# Generated by Django 5.2.7 on 2025-12-23 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0016_alter_trainer_balance_alter_trainer_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerexperience',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerexperience',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trainerspecialization',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainerspecialization',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainerspecialization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
