# Generated by Django 5.2.7 on 2025-12-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='purpose_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
