"""
Django settings for GymGem project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
import os
import sys
from pathlib import Path
from dotenv import load_dotenv
from corsheaders.defaults import default_headers


load_dotenv()

# =============================================================================
# LOGGING CONFIGURATION
# =============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'json': {
            'format': '{"level": "%(levelname)s", "time": "%(asctime)s", "module": "%(module)s", "message": "%(message)s"}',
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'stream': sys.stdout,
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(os.environ.get('LOG_DIR', '.'), 'gymgem.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(os.environ.get('LOG_DIR', '.'), 'gymgem_errors.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'gymgem': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'gymgem.auth': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'gymgem.payment': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'gymgem.websocket': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'gymgem.celery': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-secret-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

SITE_ID = 1

# Application definition
AUTH_USER_MODEL = 'accounts.Account'

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'channels',
    'django_filters',
    'channels_redis',
    'django.contrib.staticfiles',
    #external apps
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    #internal apps
    'rest_framework.authtoken',
    'django.contrib.sites',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'profiles',
    'utils',
    'accounts',
    'authenticationAndAuthorization',
    'trainers',
    'trainees',
    'gyms',    
    'stores',
    'api',
    'courses',
    'chat',
    'interactive_sessions',
    'community',
    'payment'
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",  # standard django backend
    "allauth.account.auth_backends.AuthenticationBackend",  # all auth backend
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "accounts.middleware.RateLimitMiddleware",
]

ROOT_URLCONF = "GymGem.urls"

# Frontend URL for email verification links
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:4040")

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4040",
    "http://127.0.0.1:4040",
    "https://gymgem-theta.vercel.app",
    "http://192.168.1.7:4040",
    "http://192.168.1.2:4040",
    "http://192.168.1.5:4040",
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = list(default_headers) + [
    "refresh",
]
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = 'GymGem.wsgi.application'
ASGI_APPLICATION = "GymGem.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
        "HOST": os.environ.get("POSTGRES_HOST"),
        "PORT": os.environ.get("POSTGRES_PORT"),
        "CONN_MAX_AGE": int(os.environ.get("CONN_MAX_AGE", 60)),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_SIGNUP_FIELDS = ['email*','username*','password1*','password2*'] 
ACCOUNT_EMAIL_VERIFICATION = "none"
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
REST_FRAMEWORK = {
'DEFAULT_AUTHENTICATION_CLASSES': (
'rest_framework_simplejwt.authentication.JWTAuthentication',
),
'DEFAULT_PERMISSION_CLASSES': (
'rest_framework.permissions.IsAuthenticated',
            "utils.permissions.AllowSuperuserBypass",
),
'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',

'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
'PAGE_SIZE': 10,

'DEFAULT_FILTER_BACKENDS': [
    'django_filters.rest_framework.DjangoFilterBackend',
    'rest_framework.filters.SearchFilter',
    'rest_framework.filters.OrderingFilter',
]
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'GymGem API',
    'DESCRIPTION': 'API documentation for the GymGem application',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'ENUM_NAME_OVERRIDES': {
        'StatusEnum': [
            ('draft', 'Draft'), 
            ('published', 'Published')
        ],
        'EnrollmentStatusEnum': [
            ('in_progress', 'In Progress'), 
            ('completed', 'Completed'), 
            ('dropped', 'Dropped')
        ],
    },
    # Auto-generate documentation for views without explicit serializers
    'AUTO_SCHEMA': 'drf_spectacular.openapi.AutoSchema',
    'SCHEMA_PATH_PREFIX': '/api/',
    'DEFAULT_GENERATOR_CLASS': 'drf_spectacular.generators.SchemaGenerator',
    # Group operations by tags
    'TAGS': [
        {'name': 'Accounts', 'description': 'User account operations'},
        {'name': 'Authentication', 'description': 'Login, logout, token operations'},
        {'name': 'Chat', 'description': 'Real-time chat and messaging operations'},
        {'name': 'Courses', 'description': 'Course management operations'},
        {'name': 'Trainers', 'description': 'Trainer profile and operations'},
        {'name': 'Profiles', 'description': 'User profile operations'},
        {'name': 'Trainees', 'description': 'Trainee profile and operations'},
        {'name': 'Interactive Sessions', 'description': '1:1 interactive session operations'},
        {'name': 'Utils', 'description': 'Utility endpoints (categories, etc.)'},
    ],
}

# dj-rest-auth / allauth registration deprecation fixes
# Configure SIGNUP_FIELDS to avoid deprecated USERNAME_REQUIRED/EMAIL_REQUIRED usage
REST_AUTH = {
    'SIGNUP_FIELDS': {
        'username': {'required': True},
        'email': {'required': True},
        'password1': {'required': True},
        'password2': {'required': True},
    }
}

# Suppress noisy third-party deprecation warnings in development
import warnings
warnings.filterwarnings(
    "ignore",
    message=r".*app_settings\.USERNAME_REQUIRED is deprecated.*",
    module=r"dj_rest_auth\.registration\.serializers"
)
warnings.filterwarnings(
    "ignore",
    message=r".*app_settings\.EMAIL_REQUIRED is deprecated.*",
    module=r"dj_rest_auth\.registration\.serializers"
)
warnings.filterwarnings(
    "ignore",
    message=r".*allauth\.headless\.tokens\.base\.AbstractTokenStrategy is deprecated.*",
    module=r"allauth\.headless\.tokens\.base"
)

SIMPLE_JWT = {
  # It will work instead of the default serializer(TokenObtainPairSerializer).
    "ACCESS_TOKEN_LIFETIME": timedelta(seconds=int(os.environ.get('JWT_ACCESS_TOKEN_LIFETIME', 6000))),
    "REFRESH_TOKEN_LIFETIME": timedelta(seconds=int(os.environ.get('JWT_REFRESH_TOKEN_LIFETIME', 86400))),
    "ALGORITHM": os.environ.get('JWT_ALGORITHM', 'HS256'),
    "AUTH_HEADER_TYPES": ("Bearer",),
    "TOKEN_OBTAIN_SERIALIZER": "authenticationAndAuthorization.serializers.MyTokenObtainPairSerializer",
    # Enable token blacklisting support (install app + migrate)
    "BLACKLIST_AFTER_ROTATION": False,
    "ROTATE_REFRESH_TOKENS": False,
    # ... other settings can go here
}

# Django Channels Configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")],
            # Optional configuration
            "capacity": 1500,  # Max messages in channel before dropping
            "expiry": 10,      # Message expiry time in seconds
        },
    }
}

# For development/testing without Redis, uncomment this instead:
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     }
# }

# Celery Configuration
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://127.0.0.1:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Celery Beat Schedule - Periodic Tasks
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'delete-old-messages-daily': {
        'task': 'chat.cron.delete_old_messages',
        'schedule': crontab(day_of_week=0, hour=3),  # Every Sunday at 3 AM
    },
    'expire-unaccepted-sessions': {
        'task': 'interactive_sessions.cron.handle_unaccepted_sessions',
        'schedule': crontab(minute='*/10'),
    },
    'expire-requested-sessions': {
        'task': 'interactive_sessions.cron.expire_requested_sessions',
        'schedule': crontab(minute='*/15'),
    },
        "weekly-safe-cashout": {
        "task": "profiles.tasks.run_safe_cashout_task",
        "schedule": crontab(day_of_week=0, hour=4, minute=0),
    },
}

GOOGLE_CLIENT_ID = os.environ.get('GOOGLE_CLIENT_ID')

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("gmail_user")
EMAIL_HOST_PASSWORD = os.getenv("gmail_app_password")
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 30

# Paymob Configuration
PAYMOB_API_KEY = os.getenv("PAYMOB_API_KEY")
PAYMOB_CARD_INTEGRATION_ID = int(os.getenv("PAYMOB_CARD_INTEGRATION_ID", 0))
PAYMOB_IFRAME_ID = os.getenv("PAYMOB_IFRAME_ID")
PAYMOB_HMAC_SECRET = os.getenv("PAYMOB_HMAC_SECRET")

# =============================================================================
# REDIS CONFIGURATION (Centralized)
# =============================================================================
REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")
REDIS_HOST = os.environ.get("REDIS_HOST", "127.0.0.1")
REDIS_PORT = int(os.environ.get("REDIS_PORT", 6379))
REDIS_DB = int(os.environ.get("REDIS_DB", 0))
REDIS_PASSWORD = os.environ.get("REDIS_PASSWORD", None)

# =============================================================================
# CACHING CONFIGURATION
# =============================================================================
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {"max_connections": 50},
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        },
        "KEY_PREFIX": "gymgem",
        "TIMEOUT": 300,  # 5 minutes default
    }
}

# Cache time-to-live settings (in seconds)
CACHE_TTL = {
    'categories': 3600,       # 1 hour - rarely change
    'specializations': 3600,  # 1 hour - rarely change
    'levels': 3600,           # 1 hour - rarely change
    'languages': 3600,        # 1 hour - rarely change
    'trainer_profile': 300,   # 5 minutes
    'course_list': 120,       # 2 minutes
    'course_detail': 180,     # 3 minutes
}

# Use Redis for session storage as well
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# =============================================================================
# RATE LIMITING CONFIGURATION (django-ratelimit)
# =============================================================================
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_ENABLE = True
RATELIMIT_VIEW_HANDLER = 'GymGem.ratelimit_handlers.ratelimit_handler'

# Rate limit settings
RATELIMIT_SETTINGS = {
    'login': '5/m',           # 5 login attempts per minute
    'register': '3/m',        # 3 registration attempts per minute
    'password_reset': '3/h',  # 3 password reset attempts per hour
    'payment': '10/m',        # 10 payment attempts per minute
    'api_default': '100/m',   # 100 API calls per minute (general)
    'websocket': '60/m',      # 60 WebSocket connections per minute
}
