# Generated by Django 5.2.7 on 2025-10-28 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_uniq_account_profiletype'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='default_profile',
        ),
        migrations.AddField(
            model_name='account',
            name='default_profile',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='default_for_accounts',
                to='profiles.profile',
            ),
        ),
    ]
