# Generated by Django 5.2.7 on 2025-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='admin_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, null=True),
        ),
    ]
