# Generated by Django 5.2.7 on 2025-12-21 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_alter_trainee_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
