# Generated by Django 5.2.7 on 2025-11-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0002_remove_trainee_age_trainee_balance_trainee_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
