# Generated by Django 5.2.7 on 2025-12-22 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainees', '0003_alter_trainee_balance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='trainee_records',
            new_name='TraineeRecords',
        ),
    ]
