# Generated by Django 5.2.7 on 2025-10-18 23:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('discount', models.SmallIntegerField(default=0)),
                ('duration', models.DurationField()),
            ],
            options={
                'db_table': 'packages',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_picture', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utiles.status')),
            ],
            options={
                'db_table': 'gyms',
            },
        ),
        migrations.CreateModel(
            name='GymBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, to='gyms.gym')),
            ],
            options={
                'db_table': 'gym_branches',
            },
        ),
        migrations.CreateModel(
            name='GymSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('mix', 'Mixed')], max_length=3)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='gyms.gymbranch')),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, to='gyms.gym')),
            ],
            options={
                'db_table': 'gym_slots',
            },
        ),
        migrations.CreateModel(
            name='GymService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(db_column='branch_id', on_delete=django.db.models.deletion.CASCADE, to='gyms.gymbranch')),
                ('gym', models.ForeignKey(db_column='gym_id', on_delete=django.db.models.deletion.CASCADE, to='gyms.gym')),
                ('service', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='gyms.service')),
            ],
            options={
                'db_table': 'gym_services',
                'unique_together': {('gym', 'service', 'branch')},
            },
        ),
    ]
