# Generated by Django 5.2.7 on 2025-12-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='profile_picture',
            field=models.URLField(blank=True, help_text="Link to the gym's profile picture", max_length=500, null=True),
        ),
    ]
