# Generated by Django 5.2.7 on 2025-12-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='order',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
