# Generated by Django 5.2.7 on 2025-12-05 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courselesson_order_alter_lessonsection_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselesson',
            name='order',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='order',
            field=models.PositiveIntegerField(),
        ),
    ]
