# Generated by Django 5.2.7 on 2025-12-06 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courselesson_order_alter_lessonsection_order'),
        ('profiles', '0002_alter_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='trainee_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='courselesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.courselesson'),
        ),
    ]
