# Generated by Django 5.2.7 on 2025-12-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courseenrollment_trainee_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('wishlist', 'Wishlist')], default='in_progress', max_length=20),
        ),
    ]
