# Generated by Django 5.2.7 on 2025-12-08 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseenrollment_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
