# Generated by Django 5.2.7 on 2025-12-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courseenrollment_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
