# Generated by Django 5.2.7 on 2025-12-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessonsection_is_done'),
        ('profiles', '0002_alter_profile_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonsection',
            name='is_done',
        ),
        migrations.CreateModel(
            name='CourseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lessonsection')),
                ('trainee_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
            ],
        ),
    ]
