# Generated by Django 5.2.7 on 2025-12-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_lessonsection_is_done_courseprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(default=True),
        ),
    ]
