# Generated by Django 5.2.7 on 2025-12-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courseprogress_is_completed'),
        ('profiles', '0002_alter_profile_account'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='courseprogress',
            constraint=models.UniqueConstraint(fields=('lesson_section', 'trainee_profile'), name='uniq_courseprogress_trainee_section'),
        ),
    ]
