# Generated by Django 5.2.7 on 2025-12-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_courseprogress_uniq_courseprogress_trainee_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
