# Generated by Django 5.2.7 on 2025-12-23 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_is_deleted_courselesson_is_deleted_and_more'),
        ('profiles', '0002_alter_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='trainer_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.profile'),
        ),
    ]
