# Generated by Django 5.2.7 on 2025-12-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_course_trainer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
