# Generated by Django 5.2.7 on 2026-01-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_admin_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('Request to publish', 'Request to publish')], default='draft', max_length=20),
        ),
    ]
