# Generated by Django 5.2.7 on 2025-11-22 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        ('trainers', '0002_remove_trainercalendarslot_slot_end_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='interactive_sessions', to='profiles.profile')),
                ('scheduled_at', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_sessions', to='trainers.trainercalendarslot')),
            ],
        ),
    ]
