# Generated by Django 5.2.7 on 2025-11-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactivesession',
            old_name='participants',
            new_name='first_participant',
        ),
        migrations.AddField(
            model_name='interactivesession',
            name='second_participant',
            field=models.ManyToManyField(blank=True, related_name='interactive_sessions_second', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='interactivesession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=20),
        ),
    ]
