# Generated by Django 5.2.7 on 2025-12-20 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0002_rename_participants_interactivesession_first_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactivesession',
            old_name='second_participant',
            new_name='trainee',
        ),
        migrations.RenameField(
            model_name='interactivesession',
            old_name='first_participant',
            new_name='trainer',
        ),
        migrations.AlterField(
            model_name='interactivesession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('aborted', 'Aborted'), ('refunded', 'Refunded')], default='requested', max_length=20),
        ),
    ]
