# Generated by Django 5.2.7 on 2025-12-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0003_rename_second_participant_interactivesession_trainee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivesession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending', 'Pending'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('aborted', 'Aborted'), ('refunded', 'Refunded'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
