# Generated by Django 5.2.7 on 2025-12-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0004_alter_interactivesession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivesession',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='interactivesession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('aborted', 'Aborted'), ('refunded', 'Refunded'), ('rejected', 'Rejected'), ('live', 'Live')], default='requested', max_length=20),
        ),
    ]
