# Generated by Django 5.2.7 on 2025-12-21 15:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0005_interactivesession_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivesession',
            name='fees',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(50)]),
        ),
    ]
