# Generated by Django 5.2.7 on 2025-12-22 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0006_alter_interactivesession_fees'),
        ('profiles', '0002_alter_profile_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interactivesession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interactivesession',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interactivesession',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('aborted', 'Aborted'), ('refunded', 'Refunded'), ('rejected', 'Rejected'), ('live', 'Live'), ('waiting', 'Waiting for Trainee'), ('no_show', 'No Show')], default='requested', max_length=20),
        ),
        migrations.RemoveField(
            model_name='interactivesession',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='interactivesession',
            name='trainer',
        ),
        migrations.AddField(
            model_name='interactivesession',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactive_sessions_trainee', to='profiles.profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interactivesession',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactive_sessions_trainer', to='profiles.profile'),
            preserve_default=False,
        ),
    ]
