# Generated by Django 5.2.7 on 2025-12-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0008_alter_interactivesession_trainee_and_more'),
        ('profiles', '0002_alter_profile_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivesession',
            name='trainee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactive_sessions_trainee', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='interactivesession',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interactive_sessions_trainer', to='profiles.profile'),
        ),
    ]
