# Generated by Django 5.2.7 on 2025-12-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0010_alter_interactivesession_trainee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivesession',
            name='total_active_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
