# Generated by Django 5.2.7 on 2025-12-31 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_sessions', '0011_interactivesession_total_active_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivesession',
            name='financials_applied',
            field=models.BooleanField(default=False),
        ),
    ]
