# Generated by Django 5.2.7 on 2025-10-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    run_before = [
        ('actors', '0001_initial'),
    ]
    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('course', 'Course'), ('item', 'Item')], default='course', max_length=10)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('user', 'User'), ('course', 'Course'), ('gym', 'Gym'), ('store', 'Store'), ('invoice', 'Invoice')], default='user', max_length=10)),
            ],
            options={
                'db_table': 'status',
                'constraints': [models.CheckConstraint(condition=models.Q(('type__in', ['user', 'course', 'gym', 'store', 'invoice'])), name='status_type_valid')],
            },
        ),
    ]
