# Generated by Django 5.2.7 on 2026-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='admin_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
