# Generated by Django 5.2.7 on 2025-12-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_phone_number_alter_store_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
