# Generated by Django 5.2.7 on 2025-12-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storeitemsize_alter_store_profile_picture_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='storeitem',
            name='size_id',
        ),
        migrations.CreateModel(
            name='StoreItemInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('size_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stores.storeitemsize')),
                ('store_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeitem')),
            ],
        ),
        migrations.AlterField(
            model_name='inventorylog',
            name='store_item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.storeiteminventory'),
        ),
    ]
