# Generated by Django 5.2.7 on 2025-12-31 18:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_storebranch_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebranch',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
