# Generated by Django 5.2.7 on 2025-12-31 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_storebranch_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebranch',
            name='balance',
        ),
        migrations.AddField(
            model_name='store',
            name='balance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
