# Generated by Django 5.2.7 on 2026-01-01 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_storebranch_balance_store_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='item_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='price',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
