# Generated by Django 5.2.7 on 2026-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_storeitem_item_image_alter_storeitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending')], default='draft', max_length=20),
        ),
    ]
