# Generated by Django 5.2.7 on 2026-01-11 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_cashoutreport_status'),
        ('stores', '0007_storeitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
    ]
