# Generated by Django 5.2.7 on 2026-01-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_alter_order_buyer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeitem',
            name='category',
            field=models.CharField(blank=True, choices=[('supplements', 'Supplements'), ('clothes', 'Clothes'), ('foods', 'Foods'), ('accessories', 'Accessories')], max_length=100, null=True),
        ),
    ]
